server:
  port: 9004
  servlet:
    context-path: /news-micro

spring:
  application:
    name: categoryserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaee?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: Asia/Shanghai
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com:
      ning:
        mapper: debug

mybatis:
  mapper-locations: com/ning/mapper/*.xml

pagehelper:
  helper-dialect: mysql
